export const GET_ARTISTS = "GET_ARTISTS";
export const LOAD_FILTERED_ARTISTS = "LOAD_FILTERED_ARTISTS";
export const DELETE_ARTIST = "DELETE_ARTIST";
export const CREATE_ARTIST = "CREATE_ARTIST";
export const UPDATE_ARTIST = "UPDATE_ARTIST";

